// <auto-generated />
namespace ShiftManagementHelper.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.0-30225")]
    public sealed partial class improvingDataStructure1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(improvingDataStructure1));
        
        string IMigrationMetadata.Id
        {
            get { return "202105252010552_improvingDataStructure1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
